- name: Create Release
  if: startsWith(github.ref, 'refs/tags/')
  uses: softprops/action-gh-release@v1
  with:
    files: |
      build/**/VST3/*.vst3
      build/**/AU/*.component  
      build/**/AAX/*.aax
