name: AutoRelease

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, windows-latest]
        build_type: [Release]  # Only Release for releases

    runs-on: ${{ matrix.os }}

    steps:
    - name: List Xcode installations
      if: matrix.os == 'macos-14'
      run: sudo ls -1 /Applications | grep "Xcode"
    - name: Select Xcode 16.2
      if: matrix.os == 'macos-14'
      run: sudo xcode-select -s /Applications/Xcode_16.2.0.app/Contents/Developer
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Upload Plugin Binaries
      uses: actions/upload-artifact@v4
      with:
        name: plugin-${{ matrix.os }}
        path: |
          ${{github.workspace}}/build/**/*.vst3
          ${{github.workspace}}/build/**/*.component
          ${{github.workspace}}/build/**/*.aax

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Development Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: dev-${{ github.run_number }}
        name: Development Build ${{ github.run_number }}
        prerelease: true
        files: "**/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
